version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: test-db
    restart: always
    ports:
      - 5433:5433
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: test-db
